/**
 * One-shot ingester for "NEW de Copia de Questions - Small scale sports - 21 abril.docx"
 * → Small-scale Partnerships in Youth KA210-YOU SPORTS program.
 *
 * What it does:
 *  1. Reads pre-extracted text from .tmp/criterios_sports_raw.txt
 *  2. Parses each question block (title, description, INTENCIÓN, ELEMENTOS, EJEMPLOS, EVITAR)
 *  3. For question 4.1, splits into 5 criteria (WP1..WP5)
 *  4. Writes Part A (general_context, connects_from, connects_to, global_rule)
 *     grounded in Small-scale Partnerships in Youth SPORTS context
 *  5. Replaces existing criteria for those questions + UPDATEs eval_questions
 *
 * Usage: node scripts/ingest_criterios_sports.js
 */
require('dotenv').config();
const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
const crypto = require('crypto');

const PROGRAM_NAME_LIKE = '%Small-scale%SPORTS%';
const RAW_TXT = path.join(__dirname, '..', '.tmp', 'criterios_sports_raw.txt');

// ═══════════════════════════════════════════════════════════════
// PART A — Narrative question-level block (generated by me,
// grounded in Small-scale Partnerships in Youth KA210-YOU SPORTS)
// ═══════════════════════════════════════════════════════════════

const SMALL_SCALE_GLOBAL = 'Small-scale logic: scope focalizado, objetivos limitados y ambición proporcional a un budget fijo (30.000 o 60.000€) y 6-24 meses. Evitar lenguaje propio de KA220 (gran escala). El evaluador espera un proyecto accesible para newcomers y organizaciones pequeñas.';

const PART_A = {
  '1.1': {
    general_context: 'Esta pregunta pide dos cosas a la vez: (a) explicar el problema/necesidad que el proyecto aborda en el ámbito del deporte grassroots, y (b) demostrar que encaja con el propósito de Erasmus+ Sport y con las prioridades seleccionadas. Es una de las preguntas más determinantes: incluso una buena idea saca puntuación baja si la relevancia respecto a la call no queda clara. El evaluador chequea: ¿es un problema real?, ¿a quién afecta?, ¿por qué importa ahora?, ¿qué cambio producirá el proyecto? y ¿encaja con esta call Small-scale concreta?',
    connects_from: 'Es la pregunta inicial — no hay secciones previas que la sustenten.',
    connects_to: '1.2 (Needs analysis) profundizará el problema con análisis estructurado y objetivos específicos medibles. 1.3 (Complementariedad + EU added value) ampliará el encaje europeo. 3.1 (Impact) debe medir el cambio prometido en los objetivos generales definidos aquí.',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '1.2': {
    general_context: 'El evaluador mira si existe un análisis de necesidades real y diferenciado por target group, y si los objetivos específicos responden directamente a esas necesidades de forma medible. Busca coherencia entre (necesidades identificadas → objetivos SMART → indicadores con unit/baseline/target). En Small-scale espera entre 2 y 4 objetivos específicos, no una lista exhaustiva.',
    connects_from: 'Se apoya en 1.1, que fija el problema y el rationale a alto nivel. Los objetivos generales de 1.1 se traducen aquí en objetivos específicos y medibles.',
    connects_to: 'Los objetivos e indicadores definidos aquí son la espina dorsal del resto de la propuesta: 2.1.1 (metodología) debe responder a ellos, 3.1 (impact) los medirá como outcomes, y 4.2 (WPs/actividades) los ejecutará.',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '1.3': {
    general_context: 'La pregunta busca tres cosas: (a) continuidad/aprendizaje de proyectos anteriores sin duplicar, (b) aspectos innovadores realistas (no "algo completamente nuevo"), y (c) valor añadido europeo concreto — qué produce la cooperación transnacional que no podría conseguir ninguna organización aislada. El evaluador penaliza "tenemos partners de varios países" sin explicar qué aporta esa diversidad.',
    connects_from: 'Se apoya en 1.1 (propósito del proyecto) y 1.2 (necesidades/objetivos). Sólo tiene sentido hablar de complementariedad y EU added value una vez establecido el qué y el por qué.',
    connects_to: 'Alimenta 3.1 (impact a escala europea), 3.2 (dissemination transfronteriza) y 3.3 (sustainability/transferibilidad de resultados a otros países).',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '2.1.1': {
    general_context: 'El evaluador quiere ver el proyecto como un proceso coherente, no como una lista de actividades. Busca: (a) fases claras (preparación → implementación → consolidación), (b) metodología práctica y participativa adaptada al target group, (c) justificación de por qué ese enfoque es el más adecuado para los objetivos, y (d) factibilidad dentro de los límites de una Small-scale Partnership.',
    connects_from: 'Se apoya en 1.2 (objetivos específicos) — la metodología debe responder directamente a ellos.',
    connects_to: 'Alimenta 2.1.2 (management asegura la calidad del proceso aquí descrito), 4.1 (work plan estructura este proceso en WPs) y 4.2 (actividades concretas).',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '2.1.2': {
    general_context: 'El evaluador busca prueba de que el proyecto no es sólo un diseño, sino que estará controlado durante la ejecución. Chequea: estructura de management con roles claros, planning temporal con milestones, QA continuo (no sólo evaluación final), indicadores cuantitativos + cualitativos con medida/baseline/target, y cobertura/outreach. Un management vago es una de las razones más frecuentes de puntuación baja.',
    connects_from: 'Se apoya en 2.1.1 (metodología) y 2.2.1/2.2.2 (consorcio). Los indicadores deben medir el logro de los objetivos de 1.2.',
    connects_to: 'Alimenta 2.1.5 (risk management es parte del control), 4.1 (WP1 de gestión) y 3.1 (los indicadores permiten demostrar impact).',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '2.1.3': {
    general_context: 'El evaluador quiere ver un equipo competente, equilibrado entre partners, con roles definidos y perfiles alineados con las tareas. Chequea coherencia entre: tabla de equipo (nombre/organización/rol/perfil) ↔ work plan ↔ budget A (staff). Perfiles genéricos o roles duplicados bajan la puntuación.',
    connects_from: 'Se apoya en 2.1.1 (concepto) y 2.2.1 (consorcio) — el equipo concreta la capacidad que el consorcio dice tener.',
    connects_to: 'Alimenta 4.1/4.2 (work plan — cada tarea asignada a un perfil), 2.1.4 (budget A), y 2.2.2 (management de recursos humanos).',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '2.1.4': {
    general_context: 'En Small-scale con Lump Sum Grant fijo (30.000€ o 60.000€), el evaluador no espera desglose por ítem sino una explicación breve y convincente de por qué el budget es cost-effective: uso eficiente de recursos, combinación online/presencial, aprovechamiento de facilities existentes, y estructura de gestión financiera clara (quién supervisa, cómo se reporta, cómo se monitorea).',
    connects_from: 'Se apoya en 2.1.1 (metodología determina dónde va el dinero), 2.1.3 (staff), y 4.2 (WPs con sus actividades).',
    connects_to: 'Alimenta 2.2.2 (el control financiero es parte del decision-making) y 2.1.5 (riesgos financieros).',
    global_rule: 'Small-scale con Lump Sum: NO desglosar costes por WP ni comparar ítems. Justificar cost-efficiency de forma sintética. El foco es cómo se maximizan resultados con recursos limitados, no contabilidad.'
  },
  '2.1.5': {
    general_context: 'El evaluador espera un análisis realista y proactivo de riesgos, no una lista de clichés. Chequea: mínimo ~5 riesgos bien seleccionados cubriendo dimensiones distintas (partnership, implementación, stakeholders, comunicación, administración), cada uno con likelihood + impact explícitos, vinculado a un WP, y con mitigación concreta que demuestre anticipación.',
    connects_from: 'Se apoya en 2.1.1 (metodología), 2.1.2 (management), 2.1.3 (equipo) y 2.2.1/2.2.2 (consorcio) — los riesgos emanan de todos estos elementos.',
    connects_to: 'Alimenta 2.1.2 (las medidas de mitigación son parte del sistema de control) y 4.1 (los riesgos se asocian a WPs concretos).',
    global_rule: SMALL_SCALE_GLOBAL
  },
  '2.2.1': {
    general_context: 'El evaluador busca un consorcio con propósito: cada partner debe estar por una razón clara, aportar expertise específico, y juntos cubrir todas las necesidades del proyecto. En Small-scale (mínimo 2 partners, habitualmente 2-4) es crítico evitar partners "de relleno". Pregunta guía: ¿por qué es esencial este partner aquí?',
    connects_from: 'Se apoya en 1.2 (necesidades) y 2.1.1 (metodología) — los partners se justifican por las necesidades que atienden y las tareas que ejecutan.',
    connects_to: 'Alimenta 2.1.3 (staff por partner), 2.2.2 (management del consorcio), 4.1/4.2 (distribución de WPs y actividades).',
    global_rule: SMALL_SCALE_GLOBAL + ' Consorcio pequeño: cada partner debe justificarse con claridad, sin roles duplicados.'
  },
  '2.2.2': {
    general_context: 'El evaluador mira si el proyecto está organizado sin ser excesivamente complejo. Busca: estructura clara (separación estratégico/operacional), toma de decisiones transparente (quién decide qué, cómo se consensua, qué pasa si hay desacuerdo), comunicación regular y documentada, herramientas concretas (plataformas compartidas), y un plan de planning/control con milestones. En Small-scale se espera un sistema simple y adaptado a la escala.',
    connects_from: 'Se apoya en 2.2.1 (consorcio) — el management concreta cómo colaboran en la práctica los partners descritos allí.',
    connects_to: 'Alimenta 2.1.2 (QA y monitoring operan dentro de esta estructura), 2.1.5 (risk management), y 4.1 (WP1 de coordinación).',
    global_rule: SMALL_SCALE_GLOBAL + ' Management simple, NO replicar estructuras de KA220 con comités múltiples.'
  },
  '3.1': {
    general_context: 'El evaluador busca que el proyecto describa cambios concretos, no intenciones. Debe mostrar: efectos a corto/medio/largo plazo, target groups bien definidos con beneficios observables, e indicadores medibles con unit/baseline/target ligados a los cambios prometidos. Penalizan repetir objetivos o usar verbos vacíos ("improve", "enhance") sin aterrizar qué implican.',
    connects_from: 'Se apoya en 1.2 (objetivos específicos y sus indicadores) — el impact es la materialización de esos objetivos. También en 2.1.1 (metodología) que produce los cambios, y 2.1.2 (indicadores M&E).',
    connects_to: 'Alimenta 3.2 (dissemination de resultados) y 3.3 (sustainability de los cambios más allá del proyecto).',
    global_rule: SMALL_SCALE_GLOBAL + ' Ambición realista: impact proporcional a 30-60k€ y 6-24 meses — no prometer transformación sistémica.'
  },
  '3.2': {
    general_context: 'El evaluador espera una estrategia continua y segmentada, no promoción ocasional ni genérica. Chequea: distinción clara entre comunicación (visibilidad/engagement) y dissemination (uso de resultados por otros), target groups específicos con canales adaptados, actividades cuantificadas (n° eventos, frecuencia digital), y el cumplimiento estricto de la visibilidad del EU funding.',
    connects_from: 'Se apoya en 3.1 (qué resultados hay que difundir) y 2.2.1 (partners que ejecutan dissemination).',
    connects_to: 'Alimenta 3.3 (la sustainability depende en parte de que los resultados lleguen y se usen) y 4.2 (actividades de dissemination como tarea de WP).',
    global_rule: 'Visibilidad del EU funding: obligatoria en TODOS los materiales, eventos y plataformas con emblema UE y acknowledgement. Omitirlo es un red flag crítico.'
  },
  '3.3': {
    general_context: 'El evaluador busca prueba de que la sustainability está diseñada desde el inicio, no añadida al final. Chequea: qué se mantiene concretamente (metodologías, materiales, herramientas, partnerships), cómo se integra en actividades regulares de los partners, qué recursos garantizan la continuación (staff, compromiso organizacional, posibles fondos futuros), acceso a outputs tras el fin del proyecto, y sinergias con otras iniciativas EU.',
    connects_from: 'Se apoya en 3.1 (impact a largo plazo) y 3.2 (canales/redes que siguen vivos tras el proyecto).',
    connects_to: 'Cierra el ciclo de impact — no alimenta preguntas posteriores sino que consolida las promesas de Relevance e Impact.',
    global_rule: SMALL_SCALE_GLOBAL + ' Sustainability realista: no depender sólo de "futura financiación" — demostrar recursos internos y compromiso de los partners.'
  },
  '4.1': {
    general_context: 'El evaluador espera una estructura clara del work plan con WPs coherentes entre sí. En Small-scale habitualmente: WP1 Management, WP2 Capacity building/Implementation, WP3 Pilot/Testing, WP4 M&E, WP5 Dissemination & Sustainability. Cada WP debe mostrar lógica tasks → deliverables → milestones, sin repeticiones ni huecos entre ellos.',
    connects_from: 'Se apoya en TODO el bloque de Quality (2.1.1-2.1.5) y Partnership (2.2.1-2.2.2) — el work plan es la materialización operativa de esos elementos.',
    connects_to: 'Alimenta 4.2 (descripción detallada de actividades por WP) y sirve de marco para la ejecución real del proyecto.',
    global_rule: SMALL_SCALE_GLOBAL + ' Habitualmente 4-5 WPs para Small-scale; no más. Cada WP debe ser auto-contenido pero conectado con el resto.'
  }
};

// ═══════════════════════════════════════════════════════════════
// Parser: extract question blocks from raw text
// ═══════════════════════════════════════════════════════════════

function parseRawText(text) {
  const lines = text.split('\n');
  // Find question headers: "1.1 ...", "2.1.1 ...", etc., excluding section headers "1. RELEVANCE", "2. QUALITY"
  const qRegex = /^(\d+\.\d+(?:\.\d+)?)\s+(.+?)\s*$/;
  const sectionRegex = /^\d+\.\s+[A-Z][A-Z\s]+$/;
  const wpRegex = /^Work package (\d+)\s*$/;

  const blocks = [];
  let current = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    if (sectionRegex.test(line)) continue; // skip "1. RELEVANCE", etc.
    if (line === 'PARTE 1' || line === 'PARTE 2' || line === 'CRITERIOS') continue;
    if (line === '=== TABLES ===' || line.startsWith('--- Table')) break;

    const m = line.match(qRegex);
    if (m) {
      if (current) blocks.push(current);
      current = { code: m[1], title: m[2], body: [], wps: [] };
      continue;
    }

    const wpm = line.match(wpRegex);
    if (wpm && current && current.code === '4.1') {
      current.wps.push({ wpNum: parseInt(wpm[1], 10), body: [] });
      continue;
    }

    if (current) {
      if (current.code === '4.1' && current.wps.length > 0) {
        current.wps[current.wps.length - 1].body.push(line);
      } else {
        current.body.push(line);
      }
    }
  }
  if (current) blocks.push(current);
  return blocks;
}

// Split body into criterion-like structure
function extractCriterion(lines) {
  // find indexes of headers: "Título corto", "INTENCIÓN", "ELEMENTOS", "EJEMPLOS", "EVITAR"
  const result = { description: '', tituloCorto: '', mandatory: false, intent: '', elements: '', example_weak: '', example_strong: '', avoid: '' };
  const sections = { desc: [], tit: [], intent: [], elements: [], ejemplos: [], avoid: [] };
  let current = 'desc';

  let sawTituloCorto = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^T[íi]tulo corto/i.test(line)) {
      current = 'tit';
      sections.tit.push(line);
      sawTituloCorto = true;
      continue;
    }
    // "| Category | Obligatorio" marker: only pull-back-from-desc if we haven't
    // already captured an explicit "Título corto:" line.
    if (/^\|\s*[\w\/]+\s*\|\s*Obligatorio/i.test(line)) {
      if (!sawTituloCorto) {
        for (let j = sections.desc.length - 1; j >= 0; j--) {
          const prev = sections.desc[j].trim();
          if (prev) {
            sections.tit.push(prev);
            sections.desc.splice(j, 1);
            break;
          }
        }
      }
      sections.tit.push(line);
      current = 'tit';
      continue;
    }
    if (/^INTENCIÓN$/i.test(line) || /^INTENCION$/i.test(line)) { current = 'intent'; continue; }
    if (/^ELEMENTOS$/i.test(line)) { current = 'elements'; continue; }
    if (/^EJEMPLOS/i.test(line)) { current = 'ejemplos'; continue; }
    if (/^EVITAR$/i.test(line)) { current = 'avoid'; continue; }
    sections[current].push(line);
  }

  result.description = sections.desc.join(' ').trim();

  // Title line(s) — extract short title + detect "Obligatorio"
  // Try "Título corto: ..." form first; otherwise fall back to the preceding
  // line captured right before "| Category | Obligatorio".
  const titJoined = sections.tit.join(' ');
  const titMatch = titJoined.match(/Título corto:\s*([^|]+?)(?:\s*\||$)/i);
  if (titMatch) {
    result.tituloCorto = titMatch[1].trim();
  } else {
    // Look for a line that doesn't contain "|Obligatorio" — it's the pre-marker title
    for (const l of sections.tit) {
      if (!/^\|/.test(l) && !/Título corto/i.test(l)) {
        result.tituloCorto = l.trim();
        break;
      }
    }
  }
  result.mandatory = /Obligatorio/i.test(titJoined);

  // Split ejemplos into weak/strong
  const ejem = sections.ejemplos.join(' ').trim();
  const weakIdx = ejem.search(/A\s+(?:weak|poor)\s+(?:example|risk analysis|structure)/i);
  const strongIdx = ejem.search(/A\s+strong\s+(?:example|risk analysis|structure)/i);
  if (weakIdx >= 0 && strongIdx > weakIdx) {
    result.example_weak = ejem.substring(weakIdx, strongIdx).trim();
    result.example_strong = ejem.substring(strongIdx).trim();
  } else if (strongIdx >= 0) {
    result.example_weak = ejem.substring(0, strongIdx).trim();
    result.example_strong = ejem.substring(strongIdx).trim();
  } else {
    // fallback: split by first sentence if "weak"/"strong" tokens missing
    result.example_weak = ejem;
    result.example_strong = '';
  }

  result.intent = sections.intent.join(' ').trim();
  result.elements = sections.elements.join(' ').trim();
  result.avoid = sections.avoid.join(' ').trim();
  return result;
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

async function main() {
  const raw = fs.readFileSync(RAW_TXT, 'utf8');
  const blocks = parseRawText(raw);
  console.log(`Parsed ${blocks.length} question blocks`);

  const conn = await mysql.createConnection({
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '3306', 10),
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASS || '',
    database: process.env.DB_NAME || 'eplus_tools',
    charset: 'utf8mb4'
  });

  // Find program
  const [progs] = await conn.query(
    `SELECT id, name FROM intake_programs WHERE name LIKE ?`,
    [PROGRAM_NAME_LIKE]
  );
  if (!progs.length) { console.error('Program not found'); process.exit(1); }
  const programId = progs[0].id;
  console.log(`Program: ${progs[0].name} (${programId})`);

  // Fetch existing questions for this program
  const [questions] = await conn.query(
    `SELECT eq.id, eq.code, eq.title
     FROM eval_questions eq
     JOIN eval_sections es ON eq.section_id = es.id
     WHERE es.program_id = ?`,
    [programId]
  );
  const qByCode = {};
  questions.forEach(q => { qByCode[q.code] = q; });

  let updated = 0, inserted = 0, deleted = 0;

  for (const block of blocks) {
    const q = qByCode[block.code];
    if (!q) {
      console.warn(`  ⚠ question ${block.code} not in DB (skipping)`);
      continue;
    }

    // ── Update Part A + description ──────────────────
    const partA = PART_A[block.code] || {};
    let description = null;
    if (block.code === '4.1') {
      // 4.1 body is empty (all content in wps[]), use title as description
      description = 'Provide a brief description of the overall structure of the work plan (list of work packages or graphical presentation).';
    } else {
      const crit = extractCriterion(block.body);
      description = crit.description || null;
    }

    await conn.query(
      `UPDATE eval_questions
       SET description = COALESCE(?, description),
           general_context = ?,
           connects_from = ?,
           connects_to = ?,
           global_rule = ?
       WHERE id = ?`,
      [description, partA.general_context || null, partA.connects_from || null,
       partA.connects_to || null, partA.global_rule || null, q.id]
    );
    updated++;

    // ── Delete existing criteria for this question ──────
    const [existing] = await conn.query(
      `SELECT COUNT(*) as n FROM eval_criteria WHERE question_id = ?`, [q.id]
    );
    if (existing[0].n > 0) {
      await conn.query(`DELETE FROM eval_criteria WHERE question_id = ?`, [q.id]);
      deleted += existing[0].n;
    }

    // ── Insert new criterion/criteria ──────────────────
    if (block.code === '4.1') {
      // 5 criteria (WP1..WP5)
      for (let wi = 0; wi < block.wps.length; wi++) {
        const wp = block.wps[wi];
        const crit = extractCriterion(wp.body);
        const id = crypto.randomUUID();
        await conn.query(
          `INSERT INTO eval_criteria (id, question_id, title, max_score, mandatory, priority,
           intent, elements, example_weak, example_strong, avoid, sort_order)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
          [id, q.id,
           (crit.tituloCorto || `WP${wp.wpNum}`),
           1, crit.mandatory ? 1 : 0, 'alta',
           crit.intent || null, crit.elements || null,
           crit.example_weak || null, crit.example_strong || null,
           crit.avoid || null, wi]
        );
        inserted++;
      }
    } else {
      const crit = extractCriterion(block.body);
      const id = crypto.randomUUID();
      await conn.query(
        `INSERT INTO eval_criteria (id, question_id, title, max_score, mandatory, priority,
         intent, elements, example_weak, example_strong, avoid, sort_order)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,
        [id, q.id,
         crit.tituloCorto || q.title,
         1, crit.mandatory ? 1 : 0, 'alta',
         crit.intent || null, crit.elements || null,
         crit.example_weak || null, crit.example_strong || null,
         crit.avoid || null, 0]
      );
      inserted++;
    }
    console.log(`  ✓ ${block.code} ${q.title.substring(0, 50)}`);
  }

  console.log(`\n─── Done ──────────────────────────────`);
  console.log(`Questions updated:   ${updated}`);
  console.log(`Old criteria deleted: ${deleted}`);
  console.log(`New criteria inserted: ${inserted}`);

  await conn.end();
}

main().catch(e => { console.error(e); process.exit(1); });
